import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * Convex Schema Definition
 *
 * This schema defines the data models for the application:
 * 1. animes: Stores scraped anime data and episode counts.
 * 2. subscriptions: Stores user subscriptions to specific anime.
 * 3. notificationQueue: Stores pending notifications to be processed by the bot.
 */
export default defineSchema({
  /**
   * Stores details about each scraped anime.
   * Indexed by 'url' for fast lookups during scraping.
   */
  animes: defineTable({
    url: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    subbedEpisodes: v.number(),
    dubbedEpisodes: v.number(),
    playerUrls: v.array(
      v.object({
        id: v.string(),
        text: v.string(),
        file: v.string(),
      })
    ),
    lastUpdated: v.string(),
  }).index("by_url", ["url"]),

  /**
   * Stores user subscriptions for notifications.
   * Users subscribe to a specific anime URL and type (sub/dub/all).
   */
  subscriptions: defineTable({
    telegramChatId: v.number(),
    animeUrl: v.string(),
    type: v.string(), // "sub" | "dub" | "all"
    title: v.string(),
  })
    .index("by_url", ["animeUrl"])
    .index("by_chat", ["telegramChatId"])
    .index("by_chat_and_url", ["telegramChatId", "animeUrl"]),

  /**
   * Queue for notifications generated by the scraper.
   * The bot processes this queue to send messages to subscribers.
   */
  notificationQueue: defineTable({
    animeUrl: v.string(),
    title: v.string(),
    type: v.string(), // "sub" | "dub" | "all"
    status: v.string(), // "pending" | "processed"
    createdAt: v.number(),
  })
    .index("by_status", ["status"])
    .index("by_url", ["animeUrl"]),
});
